[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ready for custom domain - uncomment when you get your domain:
# [[redirects]]
#   from = "https://dainty-licorice-6ceb5a.netlify.app/*"
#   to = "https://your-custom-domain.com/:splat"
#   status = 301
#   force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"